import { ExerciseDefinition } from '../types/database'

export const mockExercises: ExerciseDefinition[] = [
  {
    id: '0001',
    name: 'Abdominal 3/4',
    bodyPart: 'Cintura',
    equipment: 'Peso corporal',
    gifUrl: 'https://v2.exercisedb.io/image/0001',
    target: 'Abdômen',
    instructions: [
      'Deite-se de costas com os joelhos dobrados e os pés apoiados no chão.',
      'Coloque as mãos atrás da cabeça com os cotovelos apontando para fora.',
      'Contraindo o abdômen, levante lentamente a parte superior do corpo do chão, curvando-se para a frente até que seu tronco esteja em um ângulo de 45 graus.',
      'Faça uma pausa no topo e, em seguida, abaixe lentamente a parte superior do corpo de volta à posição inicial.',
      'Repita pelo número desejado de repetições.',
    ],
    secondaryMuscles: ['Flexores do quadril', 'Parte inferior das costas'],
  },
  {
    id: '0025',
    name: 'Supino Reto com Barra',
    bodyPart: 'Peito',
    equipment: 'Barra',
    gifUrl: 'https://v2.exercisedb.io/image/0025',
    target: 'Peitoral',
    instructions: [
      'Deite-se em um banco reto com os pés firmemente no chão.',
      'Segure a barra com uma pegada um pouco mais larga que a largura dos ombros.',
      'Abaixe a barra até o meio do peito, mantendo os cotovelos em um ângulo de 45 graus.',
      'Empurre a barra para cima até que seus braços estejam totalmente estendidos.',
    ],
    secondaryMuscles: ['Ombros', 'Tríceps'],
  },
  {
    id: '0783',
    name: 'Agachamento com Barra',
    bodyPart: 'Pernas (superior)',
    equipment: 'Barra',
    gifUrl: 'https://v2.exercisedb.io/image/0783',
    target: 'Quadríceps',
    instructions: [
      'Posicione a barra nas costas, sobre o trapézio.',
      'Mantenha os pés na largura dos ombros, com as pontas dos pés ligeiramente para fora.',
      'Agache-se como se fosse sentar em uma cadeira, mantendo as costas retas e o peito para cima.',
      'Desça até que suas coxas estejam pelo menos paralelas ao chão.',
      'Suba de volta à posição inicial, empurrando o chão com os calcanhares.',
    ],
    secondaryMuscles: ['Glúteos', 'Isquiotibiais', 'Panturrilhas'],
  },
  {
    id: '0007',
    name: 'Levantamento Terra com Barra',
    bodyPart: 'Costas',
    equipment: 'Barra',
    gifUrl: 'https://v2.exercisedb.io/image/0007',
    target: 'Glúteos',
    instructions: [
      'Posicione-se em frente a uma barra no chão.',
      'Agache-se e segure a barra com as mãos na largura dos ombros, com uma pegada pronada.',
      'Mantenha as costas retas, o peito para cima e o olhar para a frente.',
      'Levante a barra estendendo os quadris e os joelhos, mantendo a barra próxima ao corpo.',
      'No topo, puxe os ombros para trás e contraia os glúteos.',
      'Abaixe a barra de forma controlada, revertendo o movimento.',
    ],
    secondaryMuscles: ['Quadríceps', 'Isquiotibiais', 'Costas', 'Antebraços'],
  },
  {
    id: '0652',
    name: 'Barra Fixa (Pull-up)',
    bodyPart: 'Costas',
    equipment: 'Peso corporal',
    gifUrl: 'https://v2.exercisedb.io/image/0652',
    target: 'Dorsais',
    instructions: [
      'Segure a barra com uma pegada pronada, um pouco mais larga que os ombros.',
      'Pendure-se com os braços totalmente estendidos.',
      'Puxe seu corpo para cima até que o queixo passe da barra.',
      'Abaixe o corpo de forma controlada até a posição inicial.',
    ],
    secondaryMuscles: ['Bíceps', 'Ombros'],
  },
  {
    id: '0603',
    name: 'Desenvolvimento com Barra (Overhead Press)',
    bodyPart: 'Ombros',
    equipment: 'Barra',
    gifUrl: 'https://v2.exercisedb.io/image/0603',
    target: 'Deltoides',
    instructions: [
      'Segure a barra na altura dos ombros, com as palmas das mãos para a frente.',
      'Mantenha os pés na largura dos ombros e o abdômen contraído.',
      'Empurre a barra para cima da cabeça até que os braços estejam totalmente estendidos.',
      'Abaixe a barra de forma controlada de volta à posição inicial.',
    ],
    secondaryMuscles: ['Tríceps', 'Trapézio'],
  },
  {
    id: '0297',
    name: 'Rosca Direta com Halter',
    bodyPart: 'Braços (superior)',
    equipment: 'Haltere',
    gifUrl: 'https://v2.exercisedb.io/image/0297',
    target: 'Bíceps',
    instructions: [
      'Segure um halter em cada mão com as palmas voltadas para a frente.',
      'Mantenha os cotovelos colados ao corpo.',
      'Levante os halteres em direção aos ombros, contraindo o bíceps.',
      'Abaixe os halteres de forma controlada até a posição inicial.',
    ],
    secondaryMuscles: ['Antebraços'],
  },
  {
    id: '0564',
    name: 'Leg Press',
    bodyPart: 'Pernas (superior)',
    equipment: 'Máquina',
    gifUrl: 'https://v2.exercisedb.io/image/0564',
    target: 'Quadríceps',
    instructions: [
      'Sente-se na máquina de leg press e posicione os pés na plataforma na largura dos ombros.',
      'Empurre a plataforma para cima até que suas pernas estejam quase totalmente estendidas, sem travar os joelhos.',
      'Abaixe a plataforma de forma controlada até que seus joelhos formem um ângulo de 90 graus.',
      'Repita o movimento.',
    ],
    secondaryMuscles: ['Glúteos', 'Isquiotibiais'],
  },
  {
    id: '0642',
    name: 'Prancha',
    bodyPart: 'Cintura',
    equipment: 'Peso corporal',
    gifUrl: 'https://v2.exercisedb.io/image/0642',
    target: 'Abdômen',
    instructions: [
      'Posicione-se de bruços, apoiando o peso nos antebraços e nas pontas dos pés.',
      'Mantenha o corpo reto como uma prancha, da cabeça aos calcanhares.',
      'Contraia o abdômen e os glúteos.',
      'Segure a posição pelo tempo desejado.',
    ],
    secondaryMuscles: ['Costas', 'Ombros'],
  },
  {
    id: '3456',
    name: 'Corrida na Esteira',
    bodyPart: 'Cardio',
    equipment: 'Máquina',
    gifUrl: 'https://v2.exercisedb.io/image/3456',
    target: 'Sistema cardiovascular',
    instructions: [
      'Suba na esteira e selecione o programa desejado ou o modo manual.',
      'Comece com uma caminhada leve para aquecer.',
      'Aumente gradualmente a velocidade para o ritmo de corrida desejado.',
      'Mantenha uma postura ereta e olhe para a frente.',
      'Ao final, reduza a velocidade para uma caminhada para desaquecer antes de parar completamente.',
    ],
    secondaryMuscles: ['Pernas (superior)', 'Pernas (inferior)'],
  },
]
